// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: telegram_message.proto

package listenerserv

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// TelegramMessage is the message that must be sent
type TelegramMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest int64  `protobuf:"varint,1,opt,name=dest,proto3" json:"dest,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TelegramMessage) Reset() {
	*x = TelegramMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_telegram_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelegramMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramMessage) ProtoMessage() {}

func (x *TelegramMessage) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramMessage.ProtoReflect.Descriptor instead.
func (*TelegramMessage) Descriptor() ([]byte, []int) {
	return file_telegram_message_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramMessage) GetDest() int64 {
	if x != nil {
		return x.Dest
	}
	return 0
}

func (x *TelegramMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TelegramResponse represents the result of the call
type TelegramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Resp string `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *TelegramResponse) Reset() {
	*x = TelegramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_telegram_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelegramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramResponse) ProtoMessage() {}

func (x *TelegramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramResponse.ProtoReflect.Descriptor instead.
func (*TelegramResponse) Descriptor() ([]byte, []int) {
	return file_telegram_message_proto_rawDescGZIP(), []int{1}
}

func (x *TelegramResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TelegramResponse) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

var File_telegram_message_proto protoreflect.FileDescriptor

var file_telegram_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72,
	0x61, 0x6d, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x0f, 0x54, 0x65,
	0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x10, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x32,
	0x6a, 0x0a, 0x10, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x12, 0x56, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x21, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x6c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x22, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x75, 0x6e, 0x53, 0x69, 0x6e,
	0x63, 0x65, 0x39, 0x30, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x2d, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73,
	0x65, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_telegram_message_proto_rawDescOnce sync.Once
	file_telegram_message_proto_rawDescData = file_telegram_message_proto_rawDesc
)

func file_telegram_message_proto_rawDescGZIP() []byte {
	file_telegram_message_proto_rawDescOnce.Do(func() {
		file_telegram_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_telegram_message_proto_rawDescData)
	})
	return file_telegram_message_proto_rawDescData
}

var file_telegram_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telegram_message_proto_goTypes = []interface{}{
	(*TelegramMessage)(nil),  // 0: telegramlistener.TelegramMessage
	(*TelegramResponse)(nil), // 1: telegramlistener.TelegramResponse
}
var file_telegram_message_proto_depIdxs = []int32{
	0, // 0: telegramlistener.TelegramListener.SendMessage:input_type -> telegramlistener.TelegramMessage
	1, // 1: telegramlistener.TelegramListener.SendMessage:output_type -> telegramlistener.TelegramResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telegram_message_proto_init() }
func file_telegram_message_proto_init() {
	if File_telegram_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_telegram_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelegramMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_telegram_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelegramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_telegram_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telegram_message_proto_goTypes,
		DependencyIndexes: file_telegram_message_proto_depIdxs,
		MessageInfos:      file_telegram_message_proto_msgTypes,
	}.Build()
	File_telegram_message_proto = out.File
	file_telegram_message_proto_rawDesc = nil
	file_telegram_message_proto_goTypes = nil
	file_telegram_message_proto_depIdxs = nil
}
