apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
  namespace: kube-scraper
  labels:
    run: telegram-bot
spec:
  ports:
  - port: 80
    targetPort: 8787
    protocol: TCP
  selector:
    run: telegram-bot